name: kene
description: A USSD UI app for Mobile Money services.

version: 1.0.3+13

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.0.3
  native_contact_picker: ^0.0.6
  # firebase_core: 0.2.5+1
  firebase_analytics: ^5.0.0
  advanced_share: ^0.1.0
  firebase_auth: ^0.14.0+2
  # google_sign_in: 3.2.4
  cloud_firestore: ^0.12.9
  cached_network_image: ^1.1.1
  flushbar: ^1.8.1
  image_picker: ^0.6.1+1
  flutter_launcher_icons: ^0.7.2+1
  firebase_ml_vision: ^0.9.2+1 #for firebase machine learning kits
  flutter_spinkit: "^4.0.0" # for custom spinners
  flutter_datetime_picker: ^1.2.6 #date time picker for choosing date on signup
  package_info: ^0.4.0+6 #for getting the build info of the application
#  firebase_in_app_messaging: ^0.0.1+3 #for firebase in-app messaging
  shared_preferences: ^0.5.3+4
  auto_size_text: ^2.1.0
  firebase_messaging: ^5.1.6
  flutter_share_me: ^0.6.0
  flutter_share: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/nokanda_full.png"

flutter:
  uses-material-design: true

  assets:
    - "assets/images/nokanda.png"
    - "assets/images/nokanda_full.png"
    - "assets/images/sendmoney.png"

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf

    - family: Mali
      fonts:
        - asset: assets/fonts/Mali-Regular.ttf

    - family: Roboto-Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

    - family: Livvic
      fonts:
        - asset: assets/fonts/Livvic-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf


    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
